config/routes.rb
Rails.application.routes.draw do
  root to: "site#index"

  get "/sign_up", to: "users#new"
  post "/sign_up", to: "users#create"
  get "/profile", to: "users#show", as: :profile
  patch "/profile", to: "users#update"
  get "/profile/edit", to: "users#edit"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace "admin" do
    resources :items, except: [:show]
    resource :dashboard, only: [:show]
    resources :orders, only: [:index, :show, :update]
  end

  namespace :photos do
    resources :categories, param: :name, only: [:show]
  end

  get "/explore", to: "photos#index"
  resources :photos, only: [:show]

  get "/cart", to: "cart_photos#index"

  resources :cart_photos, only: [:create, :update, :destroy]
  resources :orders, only: [:create, :index, :show]
  resources :stores, only: [:index, :new, :create],
                     path: :photographers, as: :photographers

  get "/:photographer/edit", to: "stores#edit", as: "edit_photographer"
  get "/:photographer", to: "stores/photos#index", as: "photographer"
  patch "/:photographer", to: "stores#update"
  put "/:photographer", to: "stores#update"

  namespace :stores, path: ":photographer", as: :photographer do
    resources :photos, only: [:index, :show, :new, :create,
                              :edit, :update, :destroy]
    resources :orders, only: [:index, :show]
    resources :categories, param: :name, only: [:show]
  end
end

app/models/cart_photo.rb
class CartPhoto < SimpleDelegator
  attr_reader :quantity,
              :photo

  def initialize(photo, quantity = 0)
    super(photo)
    @photo = photo
    @quantity = quantity
  end
end

app/controllers/cart_photos_controller.rb
class CartPhotosController < ApplicationController
  def index
    @cart_photos = cart.photos
  end

  def create
    photo = Photo.find(params[:photo_id])
    cart.add_photo(photo)
    session[:cart] = cart.data
    redirect_to cart_path
  end

  def update
    cart.update_quantity(params[:id], params[:quantity])
    remove_and_render_flash(params[:id]) if cart.data[params[:id]] == 0
    redirect_to :back
  end

  def destroy
    remove_and_render_flash(params[:id])
    redirect_to :back
  end

  private

  def remove_and_render_flash(id)
    photo = Photo.find_by(id: id)
    cart.remove_from_cart(photo)
    flash[:success] = "Successfully removed #{photo.name} from your cart."
  end
end

app/views/cart_photos/index.html.erb
<!-- This is the only title not using the partial, need to figure out how to position the shopping cart with sass -->
<div class="container mt-60 mb-60">
  <div class="row mb-20">
    <div class="col-lg-12">
      <h3><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"> </span> Shopping Cart</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3"><h4>Order Details:</h4></div>
    <div class="col-md-4 col-md-offset-5">
      <div class="btn-group pull-right" role="group" aria-label="...">
        <%= link_to "Keep shopping", explore_path, class: "btn btn-warning" %>
        <%= link_to "Checkout", orders_path, method: :post, class: "btn btn-primary" %>
      </div>
    </div>
  </div>

  <div class="table-responsive">
    <table class="table table-striped">

      <tr>
        <th></th>
        <th>Photo</th>
        <th>Description</th>
        <th>Price</th>
        <th></th>
      </tr>
      <tr>
        <% @cart_photos.each do |cart_photo| %>
          <td class="col-md-1">
            <%= link_to image_tag(cart_photo.photo.image(:thumb),
                                  height: "100px", width: "100px"),
                                  photo_path(cart_photo.photo.id) %>
          </td>
          <td class="col-md-2"><%= cart_photo.name %></td>
          <td class="col-md-2"><%= cart_photo.description %></td>
          <td class="col-md-2"><%= number_to_currency(cart_photo.price) %></td>

          <td class="col-md-2">
            <%= link_to "Remove", cart_photo_path(id: cart_photo), method: :delete %>
          </td>
      </tr>
        <% end %>
        </table>

    <div class="total mt-20">
      <h3>Total: <%= number_to_currency(cart.total) %></h3>
    </div>

  </div>
</div>