config/routes.rb
Rails.application.routes.draw do
  root to: "site#index"

  get "/sign_up", to: "users#new"
  post "/sign_up", to: "users#create"
  get "/profile", to: "users#show", as: :profile
  patch "/profile", to: "users#update"
  get "/profile/edit", to: "users#edit"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace "admin" do
    resources :items, except: [:show]
    resource :dashboard, only: [:show]
    resources :orders, only: [:index, :show, :update]
  end

  namespace :photos do
    resources :categories, param: :name, only: [:show]
  end

  get "/explore", to: "photos#index"
  resources :photos, only: [:show]

  get "/cart", to: "cart_photos#index"

  resources :cart_photos, only: [:create, :update, :destroy]
  resources :orders, only: [:create, :index, :show]
  resources :stores, only: [:index, :new, :create],
                     path: :photographers, as: :photographers

  get "/:photographer/edit", to: "stores#edit", as: "edit_photographer"
  get "/:photographer", to: "stores/photos#index", as: "photographer"
  patch "/:photographer", to: "stores#update"
  put "/:photographer", to: "stores#update"

  namespace :stores, path: ":photographer", as: :photographer do
    resources :photos, only: [:index, :show, :new, :create,
                              :edit, :update, :destroy]
    resources :orders, only: [:index, :show]
    resources :categories, param: :name, only: [:show]
  end
end

app/views/shared/_errors.html.erb
<div class="row">
  <div class="col-lg-12">
    <% object.errors.full_messages.each do |message| %>
      <div class="alert alert-danger" role="alert">
        <%= message %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_photographer.html.erb
<div class="row individual-photographer">

  <a href="<%= photographer_photos_path(photographer: photographer.url) %>">
    <div class="col-md-2 photographer-contact">
      <%= image_tag photographer.avatar.url(:thumb, timestamps: false),
                    alt: photographer.name, class: "img-circle pull-left" %>
      <div class="pull-right">
        <%= photographer.name %>
        <%= photographer.email %>
      </div>
    </div>
  </a>

  <div class="photographer-photos pull-right">
    <% photographer.sample_photos.each do |photo| %>
      <a href="<%= photo_path(photo) %>"><%= image_tag photo.image.url(:thumb) %></a>
    <% end %>
  </div>
</div>